### ISSUE TITLE
atributos class e id com valores fora do padrão

### ISSUE THREAD

**Issue by mauriciomelo** [mariolucas2/mariolucas2.github.io#2]
Oi @mariolucas2 

Segue algumas dicas:

* existe alguns erros no index.html, se voce olhar na linha 37 você vai encontrar um id com o valor "informações para liberação", os atributos id e class não podem conter espaços e nem acentuação, uma sugestão é trocar por "informacoes-para-liberacao"

* na linha 22 tem  class="imagem_bloqueio", não esta errado, a dica é padronizar id e class com separação por **-** e não por **_**, então ficaria class="imagem-bloqueio"

**Comment by mariolucas2** [comment]
Opa vou concertar aqui, obrigado pela contribuição Maurício.
